from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict

class AgentState(BaseModel):
    """
    State definition for CodexEngine V2.5.
    Enforces strict typing to prevent the 'TPM Death Spiral'.
    """
    # Modern V2 configuration
    model_config = ConfigDict(arbitrary_types_allowed=True)

    # The raw input from the user
    query: str = Field(..., description="The user's original query.")
    
    # Overwrite mode (No operator.add) to prevent context dilution
    context: List[str] = Field(
        default_factory=list,
        description="Top 5 freshest prose chunks retrieved from pgvector."
    )

    # The distilled answer generated by the Actor
    answer: Optional[str] = Field(None, description="The final response generated by the Actor node.")
    
    # Metrics for the Critic (0.0 to 1.0)
    critic_score: float = Field(
        default=0.0, 
        ge=0.0, 
        le=1.0, 
        description="Deterministic score assigned by the Critic."
    )
    
    revision_count: int = Field(default=0, description="Anti-Death Spiral Counter.")
    
    estimated_tokens: int = Field(default=0, description="Throttle against 12k TPM.")

    next_step: str = Field(default="retrieve", description="Graph routing control.")